### ISSUE TITLE
Terraform credhub support

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/terraform-provider-cloudfoundry#20]
The cloudfoundry community is moving to global shared secrets and certificate, with the [credhub](https://github.com/cloudfoundry-incubator/credhub) project.

Credhub API is a simple REST API.
A terraform integration would be very useful.

Example use case:
- provision a cf service broker. Requires the broker http basic auth password. We should be able to get it from credhub in the key (/my_bosh_directot/my_service_deployment/broker_password).

cc @gberche-orange @ArthurHlt

**Comment by gberche-orange** [comment]
CredHub support in terraform should probably take the form of:
- a terraform data source [provider](https://www.terraform.io/docs/plugins/provider.html), exposing a data source (inspiration from [vault provider](https://www.terraform.io/docs/providers/vault/index.html) ). This enables reading credhub credentials and use/reference that in other resources (such as CF resources). Example of data that could be read from credhub data source include
  - the CC API endpoint and credentials for configuring the CF resource
  - name of CF resources provisioned outside of the CF terraform resources, and that can be referenced as data_source, such as system_domain that would be referenced into [cloudfoundry_domain](https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry#data-source-7)
- a terraform remote [backend](https://www.terraform.io/docs/backends/index.html), to store terraform state and plans in credhub. Currently, terraform does not support backend plugins, see https://github.com/hashicorp/terraform/issues/5877 so this would have to be contributed within terraform repo. Inspiration in the [S3 remote backend implementation](https://github.com/hashicorp/terraform/blob/master/backend/remote-state/s3/backend.go)

@poblin-orange I'm not sure this feature request lies into the cloudfoundry terraform repo. It might deserve a distinct repo. I'm renaming this issue from "Terraform credhub support" to "Terraform credhub support" as to improve discoverability

**Comment by gberche-orange** [comment]
Contributed by @ArthurHlt in 
https://github.com/orange-cloudfoundry/terraform-provider-credhub
https://github.com/orange-cloudfoundry/terraform-secure-backend
