### ISSUE TITLE
fail to update service broker

### ISSUE THREAD

**Issue by s-bortolussi** [orange-cloudfoundry/terraform-provider-cloudfoundry#21]
Service broker resource update does not seem to be applied in cloudfoundry.

Given existing service broker resource
When I update service broker password
Then service broker should be updated on CF with new password -> Failed

**Comment by ArthurHlt** [comment]
See latest release available here: https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry/releases/tag/v0.7.4 
There is no way to ensure that password change remotely (in a safety way)
