### ISSUE TITLE
Question:  Is the `routes` default value of NULL equivalent to `no-route: true` for `resource "cloudfoundry_app"` ?

### ISSUE THREAD

**Issue by snowch** [orange-cloudfoundry/terraform-provider-cloudfoundry#30]
The `resource "cloudfoundry_app"` routes parameter is defined as follows:

```
routes: (Optional, default: NULL) List of route guid retrieve from resource or data source routes to attach routes to your app.
```

Is the `routes` default value of NULL equivalent to setting the option `no-route: true`?

**Comment by ArthurHlt** [comment]
Hello @snowch ,
Yes exactly, actually `no-route` is a cf cli option. It didn't exists inside the API.

You can also have a look to https://github.com/orange-cloudfoundry/terraform-cloudfoundry-modules to push your app in a cli manifest style (but option `no-route` didn't exists too here)

**Comment by snowch** [comment]
Thanks @ArthurHlt!
