### ISSUE TITLE
Manage dependencies with glide or similar

### ISSUE THREAD

**Issue by jmcarp** [orange-cloudfoundry/terraform-provider-cloudfoundry#6]
I tried to build this locally and ran into the following:

```
../../github.com/orange-cloudfoundry/terraform-provider-cloudfoundry/cf_client/client.go:70: undefined: ccv2.NewCloudControllerClient
../../github.com/orange-cloudfoundry/terraform-provider-cloudfoundry/cf_client/terraform_repository.go:408: cannot use TerraformRepository literal (type *TerraformRepository) as type coreconfig.Repository in return argument:
        *TerraformRepository does not implement coreconfig.Repository (missing CLIVersion method)
```

I'm guessing we have different versions of the cf cli source. Should be able to fix by specifying dependencies and versions with glide, godeps, etc.

**Comment by ArthurHlt** [comment]
thanks for reporting this

I decided to not use for a moment vendoring mainly cause of issue I had with the cf cli as a dependencies, this was not a priority to fix it.

So now it has been fixed you have vendor folder inside this repo. Terraform is not in the vendor folder only to be able to switch different versions of terraform.
You can switch between those different versions like you can see in https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry/blob/master/.travis.yml#L11-L12 

You can also just let golang pull the master and that's should work.
