### ISSUE TITLE
manage user roles per space

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/terraform-provider-cloudfoundry#9]
A ressource provider to manage user space roles would be usefull

**Comment by archgrove** [comment]
Just adding my +1 for this. Some providers don't actually place the creating user into the space automatically, and then the admin user cannot manage the space. So, we can create a space using the provider, but then not actually do anything with it.

I'm working around it with a `local-exec` for now, but the ability to manage user roles would be lovely.

**Comment by gberche-orange** [comment]
@archgrove this provider is being deprecated in favor of https://github.com/mevansam/terraform-provider-cf where there is support for managing user roles within a space into https://github.com/mevansam/terraform-provider-cf/blob/master/website/docs/r/space.html.markdown and within an org using https://github.com/mevansam/terraform-provider-cf/blob/master/website/docs/r/org.html.markdown

We are in the process of migrating our tf config to use the terraform-provider-cf, possibly adding importeable support to ease it.

**Comment by archgrove** [comment]
Thanks @gberche-orange!
